name: Sync to Hugging Face Space

on:
  push:
    branches: [main]   # change to master if that's your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  # If you store large files (models/images)

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://user:$HF_TOKEN@huggingface.co/spaces/krisha09/ai-pattern-generator
          git push --force space main
